# Generated by Django 5.1.4 on 2025-08-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OHC_System', '0002_emergencycontact_profile_address_profile_blood_group_and_more'),
    ]

    operations = [
    ]
