# Generated by Django 5.1.4 on 2025-08-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHC_System', '0007_category_alter_doctor_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
