# Generated by Django 5.1.4 on 2025-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHC_System', '0008_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='healtharticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
